name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
template: |
  # What's Changed
  $CHANGES
categories:
  - title: '🚀 New Feature'
    label: 'feature'
  - title: '🧨 Hot Fixes'
    label: 'hotfix'
  - title: '🐛 Bug Fixes'
    label: 'fix'
  - title: '🛠️ Refactor'
    label: 'refactor'
  - title: '🦄 Chore'
    label: 'chore'
  - title: '📃 Document'
    label: 'document'
  - title: '📝 Lint'
    label: 'lint'
  - title: '🧪 Test'
    label: 'test'
  - title: '🤩 Release'
    label: 'release'
